name: FTP Deploy [Citymj]

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: k7ubb/citymj
          token: ${{ secrets.GITHUB_TOKEN }}
          path: citymj
          ref: main

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#
#      - name: Build Frontend
#        working-directory: ./frontend
#        run: |
#          npm ci
#          npm run build

      - name: Prepare Deploy Directory
        run: |
          mkdir -p deploy/citymj
          cp -r citymj/* deploy/citymj

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deploy/citymj/
          server-dir: /public_html/test.bb.xrea.jp/citymj/
