name: FTP Deploy [Citymj]

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout citymj
        uses: actions/checkout@v4
        with:
          repository: k7ubb/citymj
          token: ${{ secrets.GITHUB_TOKEN }}
          path: citymj
          ref: main

      - name: Prepare citymj deploy
        run: |
          mkdir -p deploy/citymj
          cp -r citymj/* deploy/citymj

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deploy/citymj/
          server-dir: /public_html/test.bb.xrea.jp/citymj/
